### ISSUE TITLE
QuickCapture - Project can't be saved due to "access to layers"

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#220]
This is a new error that just popped for us the first time today June 7th, 2022. I'll document here and then get a ticket in with Esri Support.

![image](https://user-images.githubusercontent.com/4256979/172438049-c81c9ec6-f67a-40a8-839b-bbcdb0a3a41a.png)

This error is stating "you don't have access to the layers in the project map" even though we are certain we do and did not make any recent changes to sharing. We are seeing error this in both our NAPSG Sandbox and FEMA Production environment. It appears to be since this update. https://doc.arcgis.com/en/quickcapture/faq/whatsnew.htm

This means that I can no longer make any changes to our QuickCapture Projects and save them, so it is a high priority issue.

**Comment by pjdohertygis** [comment]
Just in case it is helpful, here is what our json editor looks like - any immediate issues?


![image](https://user-images.githubusercontent.com/4256979/172439070-9ce50b46-0040-4c71-8359-7a62a0208488.png)

**Comment by IsmaelInRedlands** [comment]
Hi Paul. Definitively, this issue is caused by the latest update. By design, this warning should only appear if the web map uses layers for which the author does not have access. I setup a call later today with you. Hope you can make it, so we can debug this though screen-sharing.

**Comment by xiao8579** [comment]
Hi @pjdohertygis This error indicates that you (as the project author) currently don't have access to the feature layers that are used in the project map. Can you check if the layers have also been shared with the project author, as well as the target field users?

**Comment by pjdohertygis** [comment]
Yes indeed, sharing is all set up correctly. Furthermore, this is happening across EVERY single QuickCapture project I own where a web map is used. @xiao8579 @IsmaelInRedlands 

Things I have tried so far: 

- Project author signing in, they receive the same error, even if they own the web map as well
- Cleared cookies / browser history
- Changing the map to a generic base map (this makes the error go away, but then when I go back to a web map, I cannot save it)

**Comment by IsmaelInRedlands** [comment]
Yeap. I can repro on my own too. Researching. Looks like a bug.
Please log a Tech Support issue if you do not mind while we work on resolution.

**Comment by pjdohertygis** [comment]
Met with Esri QC Team - they think they've identified the issue as being related to grouped layers in web maps. Potential hotfix will be available later this week and will update here.

**Comment by xiao8579** [comment]
This issue has been fixed and can be verified now on the beta website https://qaext.arcgis.com/apps/quickcapture, let me know how it works on your end.

**Comment by pjdohertygis** [comment]
@xiao8579 please post back here when the hotfix is in production - thank you for all of your help!!!

**Comment by xiao8579** [comment]
Hi @pjdohertygis The fixes are on production now. https://www.arcgis.com/apps/quickcapture/

**Comment by pjdohertygis** [comment]
Confirmed and thank you Team!!!

**Comment by pjdohertygis** [comment]
We are still seeing some issues - this time not caused by grouping layers - but with mixed content sharing. @xiao8579  I'll post more screenshots for our US&R Workflow, but here is a simple one for testing. 

@avezina and I test QuickCapture MMPK workflows when we go on hikes 🤓 . In this scenario I've created a MMPK in the napsg.maps.arcgis.com envirornment and shared it into a group hosted by https://pjdohertymaps.maps.arcgis.com/. 

The QuickCapture Project is hosted in https://pjdohertymaps.maps.arcgis.com/
When I add the MMPK, which is privately shared to the QuickCapture Project, which is also privately shared into the same group, I get the following error.

![image](https://user-images.githubusercontent.com/4256979/174302064-289fbd9c-ca17-49a0-b45b-c8c538e38f05.png)

If I sign in with the napsg.maps.arcgis.com account and share the mmpk with Everyone, the error disappears! 
![image](https://user-images.githubusercontent.com/4256979/174302578-270153a7-1f3b-483d-82b1-c4a80e4c31c9.png)

When I go back to sharing the MMPK privately, I see no errors in the Network or Error console, but the Error appears in the UI and I cannot save the project. 
![image](https://user-images.githubusercontent.com/4256979/174303050-185d7220-190e-40bb-82e5-63f291f9d6ac.png)

**Comment by pjdohertygis** [comment]
Ok after troubleshooting, we *think* the final issues have been resolved and was caused by a browser cache issue. Thank you @xiao8579 for all of the support.
